parameters:
  - name: environment
    type: string
    default: "tst"
  - name: frontendAppFolder
    type: string
  - name: target
    type: string

steps:
  - script: DOCKER_BUILDKIT=1 docker build --target {{ parameters.target }} --build-arg ENV=${{ parameters.environment }} -o out .
    workingDirectory: ${{ parameters.frontendAppFolder }}